C;combination 1, 3qc7 (original info = aaaa     238     158.45  3.5e-23 0)
>P1;aaaa
structureX:aaaa: 1: : 173: : : : : 
LVISRSKEISIEVEDIKDAGDTGKRLLKINTPSGARNIIIENEDAKALINGETTNTNKKNLQDLLFSDGNVKAFLQATTTDENKTALQQLLVSNADVLGLLSGNPTSDNKINLRTMIGAGVPYSLPAATTTTLGGVKKGAAVTASTATDVATAVKDLNSLITVLKNAGIISLE

C; CA-trace Refinement
>P1;T0000
 : : : : : : : : : 
LVISRSKEISIEVEDIKDAGDTGKRLLKINTPSGARNIIIENEDAKALINGETTNTNKKNLQDLLFSDGNVKAFLQATTTDENKTALQQLLVSNADVLGLLSGNPTSDNKINLRTMIGAGVPYSLPAATTTTLGGVKKGAAVTASTATDVATAVKDLNSLITVLKNAGIISLE
