C;cover size:X; local alignment length=X (original info = aaaaA	X	X	0	0)
>P1;aaaaA
structureX:aaaaA: 1: : 173: : : :3.00: 
LVISRSKEISIEVEDIKDAGDTGKRLLKINTPSGARNIIIENEDAKALINGETTNTNKKNLQDLLFSDGNVKAFLQATTTDENKTALQQLLVSNADVLGLLSGNPTSDNKINLRTMIGAGVPYSLPAATTTTLGGVKKGAAVTASTATDVATAVKDLNSLITVLKNAGIISLE*

C;query_length:X num_of_temps:X cover_ratio:X cover:X not_cover:X
>P1;temp0_refine
 : : : : : : : : : 
LVISRSKEISIEVEDIKDAGDTGKRLLKINTPSGARNIIIENEDAKALINGETTNTNKKNLQDLLFSDGNVKAFLQATTTDENKTALQQLLVSNADVLGLLSGNPTSDNKINLRTMIGAGVPYSLPAATTTTLGGVKKGAAVTASTATDVATAVKDLNSLITVLKNAGIISLE*
