C;cover size:108; local alignment length=108 (original info = 1LM7A	238	158.45	3.5e-23	0)
>P1;1LM7A
structureX:1LM7A: 41: : 137: : : :3.00: 
-KDFLQGSSCIAGIYNETTKQKLGIYEAMKIGLVRPGTALELLEAQA---------------------------------------------------------------------ATGFIVDPVSNLRLPVEEAYKRGLVGIEFKEKLLSAERAVTGYNDPETGNI*

C;cover size:102; local alignment length=102 (original info = 1LM5A	189	144.67	7.4e-21	2)
>P1;1LM5A
structureX:1LM5A: 1: : 160: : : :1.80: 
-------SSPIAAIFDTENLEKISITEGIERGIVDSITGQRLLEAQACTGGIIHPTTGQKLSLQDAVSQGVIDQDMATRLKPAQKAFIGFKMSAAEAVKEKWLPYEAGQRFLEFQYLTGGLVDPEVHGRISTEEAIRKGFIDGRAAQRLQDTSSYAKILTCPKTKLK*

C;query_length:109 num_of_temps:1 cover_ratio:0.99 cover:108 not_cover:1
>P1;T0759
 : : : : : : : : : 
MGHHHHHHSHM-VVIHPDPGRELSPEEAHRAGLIDWNMFVKLRSQECDWEEIS---------------------------------------------------------VKGPNGESSVIHDRKSGKKFSIEEALQSGRLTPAHYDRYVNKDMSIQELAVLVSGQK*
