C;cover size:214; local alignment length=214 (original info = 4J8QA	191	294.10	0	0)
>P1;4J8QA
structureN:4J8QA: 1: : 191: : : :6.0: 
-----------------------------DGYSLGDIAVDWATVRVVGGDTYSLNADRWGTLWPAATA-IPFYKPIDGQRVITYFNPLYDNYEGYDHAVKVEHNYNVLTKQVEDLTAE--NESEFGNDPVWVNK-DWIG--GGYLNVIFRQ------NLKHLVSLVRDRATA------AEGEDDGYIHLELRYKTYDDQ----ANGAVSFNLNSLD--LTGKKGIKVKLNSVKDGETEVVFNLK*

C;cover size:207; local alignment length=207 (original info = 3K0YA	195	277.79	0	1)
>P1;3K0YA
structureN:3K0YA: 2: : 185: : : :6.0: 
------------------------------------IWIAVATVVPEGNNVYYLRLDDGDKLWPAATN-YPNYQPKPNQRALVNFTILADS-----HYIKVNAIHNILTKSIAKNEGAA-NDSIYGTDPVSIYNNNWIG--DGYLNIYFETLWG--GKTAHFINLIQPDAE-----------NDPY-TLEFRHNAYDDPQYTIGAGRVAFNLSSLPDTKGETVDLVVNYWT-SEGKQAYKLKYN*

C;template; advanced alignment combination (original info = C;cover size:102; local alignment length=102 (original info = 3KDHA	189	4.13	1.9e+03	12))
>P1;3KDHA
structureN:3KDHA:45: :83: : : :6.0: 
PASVVWPLIRRFDNPERYKHFVKRCRLISGDGDVGSVRE-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:242 num_of_temps:1 cover_ratio:0.88 cover:214 not_cover:28
>P1;T0760
 : : : : : : : : : 
MYMKKLKFITLTLAIIITLPMLQSC-LDDNDHQSRSLVISTINQISEDSKEFYFTLDNGKTMFPSNSQAWGGEKFENGQRAFVIFNELEQPVNGYDYNIQVRDITKVLTKEIVTMDDEENTEEKIGDDKINATY-MWISKDKKYLTIEFQYYSTHSEDKKHFLNLVINNKEADSAAENEDNTDDEYINLEFRHNSERDSPDHLGEGYVSFKLDKIEEQIEGKKGLNIRVRTLYDGIKNYKVQFP*
